# Generated by Django 4.0.1 on 2022-01-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('imageUrl', models.URLField()),
                ('releaseDate', models.DateTimeField(verbose_name='date released')),
                ('updatedDate', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
    ]
