# Generated by Django 4.0.1 on 2022-01-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_userrole_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='list',
            field=models.ManyToManyField(through='main.Lists', to='main.Song'),
        ),
    ]
