# Generated by Django 4.0.1 on 2022-01-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='role',
        ),
    ]
