# Generated by Django 4.0.1 on 2022-01-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_staffrole_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrole',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
