# Generated by Django 4.0.1 on 2022-01-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_genre_name_alter_song_title_alter_staff_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
        migrations.DeleteModel(
            name='StaffRole',
        ),
    ]
