# Generated by Django 4.0.1 on 2022-01-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_song_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='updatedDate',
        ),
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
