# Generated by Django 4.0.1 on 2022-01-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_song_updateddate_song_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
