# Generated by Django 4.0.1 on 2022-01-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_song_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
