# Generated by Django 4.0.1 on 2022-01-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_song_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='releaseDate',
            field=models.DateTimeField(null=True, verbose_name='date released'),
        ),
    ]
