# Generated by Django 4.0.1 on 2022-01-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_song_releasedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
