# Generated by Django 4.0.1 on 2022-01-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_song_genres_delete_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album_name',
            new_name='albumName',
        ),
    ]
