# Generated by Django 4.0.1 on 2022-01-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
