# Generated by Django 4.0.1 on 2022-01-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_user_role_delete_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='albumName',
        ),
        migrations.RemoveField(
            model_name='song',
            name='staffs',
        ),
        migrations.RenameModel(
            old_name='Staff',
            new_name='Artist',
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(to='main.Artist'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('releaseDate', models.DateTimeField()),
                ('artists', models.ManyToManyField(to='main.Artist')),
                ('songs', models.ManyToManyField(to='main.Song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(to='main.Album'),
        ),
    ]
