# Generated by Django 4.0.1 on 2022-01-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_song_albumname_remove_song_staffs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='albums',
        ),
    ]
