# Generated by Django 4.0.1 on 2022-01-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_album_spotify_id_artist_spotify_id_song_spotify_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='spotify_id',
            new_name='spotifyId',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='spotify_id',
            new_name='spotifyId',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='spotify_id',
            new_name='spotifyId',
        ),
    ]
