# Generated by Django 4.0.1 on 2022-01-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_album_artists_alter_album_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='imageUrl',
            field=models.URLField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
