# Generated by Django 4.0.1 on 2022-01-27 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_album_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
