# Generated by Django 4.0.1 on 2022-01-31 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_lists_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_artists',
            field=models.ManyToManyField(related_name='user_favourites', to='main.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='artist_songs', to='main.Artist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='user_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
