# Generated by Django 4.0.1 on 2022-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_previewurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='previewUrl',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
