# Generated by Django 4.0.1 on 2022-02-02 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song'),
        ),
        migrations.AlterField(
            model_name='lists',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.ManyToManyField(related_name='activity', through='users.Activities', to='songs.Song'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favourite_artists',
            field=models.ManyToManyField(related_name='user_favourites', to='songs.Artist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='list',
            field=models.ManyToManyField(through='users.Lists', to='songs.Song'),
        ),
    ]
